= Begriffe für Nutzende
:description: Datenthema, Datensatz, Ausgabe und Distribution aus Sicht von Nutzenden.

Diese Seite erklärt die Begriffe, die Nutzende im Datenportal beim Suchen, Verstehen und Herunterladen von Daten antreffen.

== Datenthema

Ein **Datenthema** ist die fachliche, für Nutzende verständliche Beschreibung eines Datenangebots im Datenportal. Es beantwortet die Frage: Worum geht es fachlich?

.Beispiele
* Einwohnerstatistik
* Bauzonen
* Schulstandorte
* Velounfälle
* Orthofotos

== Datensatz

Ein **Datensatz** ist eine klar beschriebene Sammlung von Daten, die als fachliche und organisatorische Einheit publiziert, gepflegt und gefunden werden kann.

Ein Datensatz ist noch nicht zwingend eine Datei. Er beschreibt das Datenangebot als inhaltliche Einheit. Die konkreten Dateien, Dienste oder Downloadformate werden als Distributionen beschrieben.

== Datensatz-Serie und Ausgabe

include::_partials/begriff-serie-und-ausgabe.adoc[]

.Beispiele
* «Orthofotos Kanton Solothurn» als Datensatz-Serie mit den Ausgaben 2021, 2023 und 2025.
* «Einwohnerstatistik 2024» als Ausgabe der Serie «Einwohnerstatistik».
* «Gemeindefinanzen Rechnungsjahr 2023» als Ausgabe der Serie «Gemeindefinanzen».

== Distribution

include::_partials/begriff-distribution.adoc[]

Eine Distribution kann eine Datei, ein Dienst oder eine API sein. Die Distribution beantwortet die Frage: Wie kann ich die Daten beziehen oder nutzen?

.Typische Distributionen
* CSV-Datei
* Excel-Datei
* Parquet-Datei
* GeoPackage
* Shapefile
* JSON oder GeoJSON
* RDF/Turtle
* Download-URL
* API-Endpunkt
* WFS
* WMS
* Kartenansicht

== Formate wählen

CSV ist sinnvoll, wenn ein sehr einfaches, breit verständliches Austauschformat genügt und die Datenmenge überschaubar ist.

XLSX ist sinnvoll, wenn Menschen die Daten manuell in einer Tabellenkalkulation anschauen, filtern oder bearbeiten sollen.

Parquet ist sinnvoll, wenn Daten maschinell, wiederholbar und performant ausgewertet werden sollen, besonders bei grösseren Tabellen oder analytischen Workflows.
